// ============================================================
// PLACEHOLDER — this file is normally generated by the FlutterFire CLI, not
// hand-written. It exists here only so the codebase compiles before the
// Firebase project has been wired up.
//
// To make push notifications actually work:
//   dart pub global activate flutterfire_cli
//   firebase login
//   flutterfire configure --project=erams-98eb2
// This overwrites this file with real per-platform keys (and also drops
// android/app/google-services.json). See docs/COMPLETED_WORK.md for the
// full manual setup checklist (VAPID key, service account JSON, etc).
//
// Every apiKey below is intentionally a `REPLACE_` sentinel — main.dart
// checks for that prefix and skips Firebase.initializeApp() entirely until
// this file has been regenerated, so the rest of the app keeps working
// without a configured Firebase project.
// ============================================================
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '$defaultTargetPlatform — ERAMS only targets web and Android.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'erams-98eb2',
    authDomain: 'erams-98eb2.firebaseapp.com',
    storageBucket: 'erams-98eb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'erams-98eb2',
    storageBucket: 'erams-98eb2.appspot.com',
  );

  /// True once this file has been regenerated by `flutterfire configure`
  /// with real keys. Checked by main.dart to decide whether it's safe to
  /// call Firebase.initializeApp() at all.
  static bool get isConfigured =>
      !currentPlatform.apiKey.startsWith('REPLACE_');
}
