// ============================================================
// Generated by the FlutterFire CLI (`flutterfire configure --project=erams-98eb2`)
// on 9 Sep 2026, then hand-merged into this path (the CLI's default output
// location is lib/firebase_options.dart; this project's code imports from
// core/config/ instead, so the generated content was moved here and the
// stray top-level copy removed to avoid two diverging sources of truth).
//
// Only web and Android are configured — this app doesn't target iOS/macOS/
// Windows/Linux. To regenerate (e.g. after rotating keys): rerun
// `flutterfire configure --project=erams-98eb2 --platforms=web,android`
// and re-merge the same way, preserving the isConfigured getter below.
// ============================================================
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '$defaultTargetPlatform — ERAMS only targets web and Android.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7-KWiBnCSnnVOKc9rzgIkaU_kvIDqLw',
    appId: '1:840423219815:web:d5c4dbab9887ef5009aac2',
    messagingSenderId: '840423219815',
    projectId: 'erams-98eb2',
    authDomain: 'erams-98eb2.firebaseapp.com',
    storageBucket: 'erams-98eb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdrHaUInK6NaetXm3piWHPcR-7noFfZMk',
    appId: '1:840423219815:android:5afad3512380df1609aac2',
    messagingSenderId: '840423219815',
    projectId: 'erams-98eb2',
    storageBucket: 'erams-98eb2.firebasestorage.app',
  );

  /// True once this file carries real (non-placeholder) keys. Checked by
  /// main.dart to decide whether it's safe to call Firebase.initializeApp()
  /// at all — kept even though this file is no longer a placeholder, so a
  /// future `git revert` back to the placeholder degrades gracefully again
  /// instead of crashing.
  static bool get isConfigured =>
      !currentPlatform.apiKey.startsWith('REPLACE_');
}
